### ISSUE TITLE
\aa redefined

### ISSUE THREAD

**Issue by davidcarlisle** [kellertuer/MathSemantics.sty#3]
The package does

```
\let\aa\undefined \newcommand{\aa}{a.a.\xspace}
```

This will redefine the standard LaTeX command `\aa` which produces å with no warning, this is highly likely to corrupt bibliographies with non-english names, and more generally any Swedish language document.

**Comment by kellertuer** [comment]
I have to think what to best do here, since anything longer would make the command irrelevant.

**Comment by davidcarlisle** [comment]
you were lucky as å expands to `\r a` so redefining `\aa` does not change it, but if for example you had redefined `\ae` then you would change the behaviour of the UTF-8 input `æ` as `æ` expands to `\ae` as it's first step, just as `ö` expands to `\"o` so if you redefine `\"` you redefine all UTF-8 letters with an umlaut.

Besides that bibtex is (still) not UTF aware so millions of bib files will have `\aa`

**Comment by kellertuer** [comment]
Sure. BibTeX is also not so much utf8. AS I wrote in the other issue, this is my first package to CTAN and currently it sounds like it would not meet the quality standards usually enforced. Sorry for that.

**Comment by davidcarlisle** [comment]
don't feel too bad, ctan doesn't enforce standards really (and this is far from being the worst) It just had an interesting name so I looked, and it clashed with a package I wrote, so I complained:-)

**Comment by kellertuer** [comment]
Ok :)

One could introduce a `\tlab{a}{a}` (two letter abbreviation) to get the spacing right, and then, ... hm I will think about this.

**Comment by u-fischer** [comment]
you could  use a package like acro or glossaries for the abbreviations.

**Comment by kellertuer** [comment]
For the names, sure. I will think about that.
